/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AbecedarioRouteImport } from './routes/abecedario'
import { Route as InicialRouteImport } from './routes/inicial'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as MonosilabasRouteImport } from './routes/monosilabas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AbecedarioRoute = AbecedarioRouteImport.update({
  id: '/abecedario',
  path: '/abecedario',
  getParentRoute: () => rootRouteImport,
} as any)
const InicialRoute = InicialRouteImport.update({
  id: '/inicial',
  path: '/inicial',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const MonosilabasRoute = MonosilabasRouteImport.update({
  id: '/monosilabas',
  path: '/monosilabas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abecedario': typeof AbecedarioRoute
  '/inicial': typeof InicialRoute
  '/menu': typeof MenuRoute
  '/monosilabas': typeof MonosilabasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abecedario': typeof AbecedarioRoute
  '/inicial': typeof InicialRoute
  '/menu': typeof MenuRoute
  '/monosilabas': typeof MonosilabasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abecedario': typeof AbecedarioRoute
  '/inicial': typeof InicialRoute
  '/menu': typeof MenuRoute
  '/monosilabas': typeof MonosilabasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/abecedario' | '/inicial' | '/menu' | '/monosilabas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/abecedario' | '/inicial' | '/menu' | '/monosilabas'
  id: '__root__' | '/' | '/abecedario' | '/inicial' | '/menu' | '/monosilabas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbecedarioRoute: typeof AbecedarioRoute
  InicialRoute: typeof InicialRoute
  MenuRoute: typeof MenuRoute
  MonosilabasRoute: typeof MonosilabasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abecedario': {
      id: '/abecedario'
      path: '/abecedario'
      fullPath: '/abecedario'
      preLoaderRoute: typeof AbecedarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inicial': {
      id: '/inicial'
      path: '/inicial'
      fullPath: '/inicial'
      preLoaderRoute: typeof InicialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monosilabas': {
      id: '/monosilabas'
      path: '/monosilabas'
      fullPath: '/monosilabas'
      preLoaderRoute: typeof MonosilabasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbecedarioRoute: AbecedarioRoute,
  InicialRoute: InicialRoute,
  MenuRoute: MenuRoute,
  MonosilabasRoute: MonosilabasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
