/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AbecedarioRouteImport } from './routes/abecedario'
import { Route as EmocionesRouteImport } from './routes/emociones'
import { Route as InicialRouteImport } from './routes/inicial'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as MonosilabasRouteImport } from './routes/monosilabas'
import { Route as SenasRouteImport } from './routes/senas'
import { Route as SilabasRouteImport } from './routes/silabas'
import { Route as VocabularioRouteImport } from './routes/vocabulario'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AbecedarioRoute = AbecedarioRouteImport.update({
  id: '/abecedario',
  path: '/abecedario',
  getParentRoute: () => rootRouteImport,
} as any)
const EmocionesRoute = EmocionesRouteImport.update({
  id: '/emociones',
  path: '/emociones',
  getParentRoute: () => rootRouteImport,
} as any)
const InicialRoute = InicialRouteImport.update({
  id: '/inicial',
  path: '/inicial',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const MonosilabasRoute = MonosilabasRouteImport.update({
  id: '/monosilabas',
  path: '/monosilabas',
  getParentRoute: () => rootRouteImport,
} as any)
const SenasRoute = SenasRouteImport.update({
  id: '/senas',
  path: '/senas',
  getParentRoute: () => rootRouteImport,
} as any)
const SilabasRoute = SilabasRouteImport.update({
  id: '/silabas',
  path: '/silabas',
  getParentRoute: () => rootRouteImport,
} as any)
const VocabularioRoute = VocabularioRouteImport.update({
  id: '/vocabulario',
  path: '/vocabulario',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abecedario': typeof AbecedarioRoute
  '/emociones': typeof EmocionesRoute
  '/inicial': typeof InicialRoute
  '/menu': typeof MenuRoute
  '/monosilabas': typeof MonosilabasRoute
  '/senas': typeof SenasRoute
  '/silabas': typeof SilabasRoute
  '/vocabulario': typeof VocabularioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abecedario': typeof AbecedarioRoute
  '/emociones': typeof EmocionesRoute
  '/inicial': typeof InicialRoute
  '/menu': typeof MenuRoute
  '/monosilabas': typeof MonosilabasRoute
  '/senas': typeof SenasRoute
  '/silabas': typeof SilabasRoute
  '/vocabulario': typeof VocabularioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abecedario': typeof AbecedarioRoute
  '/emociones': typeof EmocionesRoute
  '/inicial': typeof InicialRoute
  '/menu': typeof MenuRoute
  '/monosilabas': typeof MonosilabasRoute
  '/senas': typeof SenasRoute
  '/silabas': typeof SilabasRoute
  '/vocabulario': typeof VocabularioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abecedario'
    | '/emociones'
    | '/inicial'
    | '/menu'
    | '/monosilabas'
    | '/senas'
    | '/silabas'
    | '/vocabulario'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abecedario'
    | '/emociones'
    | '/inicial'
    | '/menu'
    | '/monosilabas'
    | '/senas'
    | '/silabas'
    | '/vocabulario'
  id:
    | '__root__'
    | '/'
    | '/abecedario'
    | '/emociones'
    | '/inicial'
    | '/menu'
    | '/monosilabas'
    | '/senas'
    | '/silabas'
    | '/vocabulario'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbecedarioRoute: typeof AbecedarioRoute
  EmocionesRoute: typeof EmocionesRoute
  InicialRoute: typeof InicialRoute
  MenuRoute: typeof MenuRoute
  MonosilabasRoute: typeof MonosilabasRoute
  SenasRoute: typeof SenasRoute
  SilabasRoute: typeof SilabasRoute
  VocabularioRoute: typeof VocabularioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abecedario': {
      id: '/abecedario'
      path: '/abecedario'
      fullPath: '/abecedario'
      preLoaderRoute: typeof AbecedarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emociones': {
      id: '/emociones'
      path: '/emociones'
      fullPath: '/emociones'
      preLoaderRoute: typeof EmocionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inicial': {
      id: '/inicial'
      path: '/inicial'
      fullPath: '/inicial'
      preLoaderRoute: typeof InicialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monosilabas': {
      id: '/monosilabas'
      path: '/monosilabas'
      fullPath: '/monosilabas'
      preLoaderRoute: typeof MonosilabasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/senas': {
      id: '/senas'
      path: '/senas'
      fullPath: '/senas'
      preLoaderRoute: typeof SenasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/silabas': {
      id: '/silabas'
      path: '/silabas'
      fullPath: '/silabas'
      preLoaderRoute: typeof SilabasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vocabulario': {
      id: '/vocabulario'
      path: '/vocabulario'
      fullPath: '/vocabulario'
      preLoaderRoute: typeof VocabularioRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbecedarioRoute: AbecedarioRoute,
  EmocionesRoute: EmocionesRoute,
  InicialRoute: InicialRoute,
  MenuRoute: MenuRoute,
  MonosilabasRoute: MonosilabasRoute,
  SenasRoute: SenasRoute,
  SilabasRoute: SilabasRoute,
  VocabularioRoute: VocabularioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
